### ISSUE TITLE
Минимальная поддержка bsl-файлов

### ISSUE THREAD

**Issue by artbear** [dmpas/idea-onescript#1]
Сделать минимум - поддержать расширение файла `.bsl` абсолютно также, как и `.os`

**Comment by artbear** [comment]
Упс, оказывается, поддержка есть.
+ А в ридми про это ни слова
+ У меня IDEA не сразу отрисовал правильный синтакс после перезагрузки :)

Добавишь в ридми упоминание bsl-файлов ?

**Comment by dmpas** [comment]
> Добавишь в ридми упоминание bsl-файлов ?

нет бы сразу ПР сделать, а? 😭

**Comment by artbear** [comment]
а разве после покупки Майкрософтом эта фишка осталась ? :trollface: 

сейчас сделаю

**Comment by artbear** [comment]
fix в https://github.com/dmpas/idea-onescript/pull/2
